import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'
import { AuthProvider } from './AuthProvider'
import Providers from './providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('in LAYOUT')
  return (
    <html lang="en">
      <body>
        <div>
          <AuthProvider>
<div>TOTO</div>
              <Header />
              {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
